sudo: required

services:
  - docker

language: generic

before_install:
  - TAG=$(time=$(date +%T) && echo "$(date +%F)_${time//:/.}")
  - echo "Building image 'pipeline-deployer:${TAG}'"
  - docker build --pull -t pipeline-deployer:${TAG} .

script:
  - echo "Searching for image 'pipeline-deployer:${TAG}'"
  - docker images pipeline-deployer:${TAG}