sudo: required

services:
  - docker

language: generic

env:
  global:
    DOCKERHUB_USERNAME:
      secure: "BtrqkAkA0NGgAhj5l7Lcaf9O/elVJv/1oJLVig9JyBDjh7SvH+vj/3Tbfnw6P0amPcipYdvvrHvaPSgRkIk8i2tJhI2tr7ZC/Us/9nGcgS9LP2mtvr7XJO1TN8+hma44hE3H3WU9CbWpMLQNRFnv+3ZThY7vB2cvTyMeqniawV5m9BeRSd9ZNGN4XGwtI+6fDpDQzSR9V72AzQDbWY10m3p9/Zh9I6oQZ+fYIpBDmWb89L6O0HOVYM64JZ5R5mw9nmBww8Hnhf9MQE9Ej34nSk7u5SAJm3ir92s4f7G64W9Xn9atGxcPKSWgBpWePNHJvrMSpjgFOsox+eI1UIx1uXqCO4MS82Vta0/cVxuhN2XQHPImadn1cdZA1j1ksOuWGhao/80AbD/EqnXvZJoLiVZJJ4QO8xSGSMNzUjQ0t+bFrUKTOz5S+vU4qy6yRINA5FEKCIK3wprlA/eO98EEsTUft5K56FQXvinoVudVzBmQi9QJL9MgZ3HxGbzIj4VfS0RPmADSl8+jolaixS9Z4JBO1wAbSWSL+36pChVJIyEAA5fuegEvQRCaA/5YFXZPjUQMPYdi0/miGF7kr4/T2jfcIvqzBX2xtPzUFbQDKrEKhGSuVe1D6QScaJn6w/FpyjGPfqMT7JLQUJk9fWOyD16JIPwDsrqbast6gCR+Z1c="
    DOCKERHUB_PASSWORD:
      secure: "LMjKLWxTRre/ENO4s5jLi37rBcoq/dJV7/zJDO8JdJwUDdCO3RIB7pYPINW+MQ5aoSruDE9C5MlEVaGNyGhGNvCVEC/T6pUlUXacfo8CJ3UDKXedgCC+oWNFHmSfkaoHiCLprbArMeC2oyxl99hDxeoE9YOxZsc0m48BghJXIbK3rRpdSQ5vB4p3d7d/5LPPB92xojWv/gMCMYV+1FKH5gMxZB0a4NqcVD8X1iu5bYzQVEWzZjZjUh7M5XaQyT8vaTQlCdMPKszkoi5Ue4r2k3n0fVN6XKYYqb2oR/IqenGQVSWegOslRi0YBZmHvO/oTI3aHqHblL2Nvv8odSlW4nr8zRWgBFmbyD59k7dknbWTTPZ9EiAhpKC2y8zEc6QDiTIQRM1+fRMgD/HSjSnGs6YxBITwLiiVGz5NA/wIxGamxtkjRUkcMZmTNILHDLuRkamxi0k66QkzSCAzF8kRbxr2IcvuvO47kq4a2U2+hiPN2//5mgLcDv6COCj9Rz80a+Y4scDs531hYz8oK0SKMrNcu+nIwgS5WVAuQG9YeqwnqRgZguOvfzQ/hXDd0HoAwGMDD4TJKngLMkDs4ZFSzNarCAmjamR6os73VOQEA7L+GTXDtUjxz604ney0PnJ420Pc9ed1hd5SNWboL5WzcIc+0s0+P/SAl8GGyRHxxoE="

before_install:
- VAR1=${DOCKERHUB_USERNAME}; echo $VAR1; env
- TAG=$(time=$(date +%T) && echo "$(date +%F)_${time//:/.}")
- IMAGE=pipeline-deployer
- echo "Building image '${IMAGE}:${TAG}'"
- docker build --pull -t ${IMAGE}:${TAG} .
- if [ "${TRAVIS_BRANCH}" = "master" ]; then docker tag ${IMAGE}:${TAG} ${IMAGE}:latest;
  fi

script:
- echo "Searching for image '${IMAGE}:(any tag)'"
- docker images ${IMAGE}

after_success:
- if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then exit 0; fi
- docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD};
- if [ "${TRAVIS_BRANCH}" = "master" ]; then docker push ${IMAGE}:latest; fi
- docker push ${IMAGE}:${TAG};
